server:
  port: 9080
logging:
  level:
    root: info
topic:
  name: users
  partitions-num: 6
  replication-factor: 3

spring:
  kafka:
    bootstrap-servers:
      - localhost:9092
    consumer:
      group-id: group_id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
    template:
      default-topic:

